CC=gcc
CFLAGS=-Wall -Werror
#CFLAGS+=-g
#CFLAGS+=-pg

all: msort   merge2Arrays msortPrintState

msort : msort.c

msortPrintState: msortPrintState.c

merge2Arrays : merge2Arrays.c

clean :
	rm -f msort msortPrintState merge2Arrays   *.o core
